### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JochemZ** [CodingBSilva/SteelSeries-Canvas-QlikSense#1]
is it possible not allways to start at value 0? so when values changes from 50 to 90 it only moves the arrow from 50 to 90, and not falling back to 0 and than moving to 90?

**Comment by CodingBSilva** [comment]
Hello,

To be honest I don't remember but looking to the code it seems possible.
`minValue: (undefined === layout.minValue ? 0 : layout.minValue)`

Try to look at the Layout Settings it should have a Min and Max Value.

I hope this hint helps.

Best regards,
Bruno Silva

**Comment by JochemZ** [comment]
No this does not solve my problem😥
Problem is that with Every new value the hypercube Gets the repaint Will start with 0 till the new value. So iT is allways dropping to zero.


________________________________

Met vriendelijke groet,
​
​Jochem Zwienenberg
​​Senior Business Consultant / Product Manager 
t: +31(0)74-2915208
e: jz@victa.nl
m: +31 0614305579
w: www.victa.nl
Deze email is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien deze e-mail niet voor u is bestemd, verzoeken wij u om contact op te nemen met de afzender en daarna het bericht te vernietigen. ​Alle rechten voorbehouden.
Van: B. Silva <notifications@github.com>
Verzonden: zondag, maart 10, 2019 6:28 PM
Aan: CodingBSilva/SteelSeries-Canvas-QlikSense
CC: Jochem Zwienenberg | Victa; Author
Onderwerp: Re: [CodingBSilva/SteelSeries-Canvas-QlikSense] Question (#1)


Hello,

To be honest I don't remember but looking to the code it seems possible.
minValue: (undefined === layout.minValue ? 0 : layout.minValue)

Try to look at the Layout Settings it should have a Min and Max Value.

I hope this hint helps.

Best regards,
Bruno Silva

**Comment by CodingBSilva** [comment]
Unfortunately I think the required feacture doesn't exist at the moment.
Thanks for the contact and for using my add-on.

Best regards,
Bruno Silva
